#!/bin/bash
# Lineup — FULL PAPER MATRIX to accumulate data, then curate from the live tape.
# Naming everywhere = strat-token-frame ; state dir = state_<variant>_<coin>_<frame>.
#
# 2026-06-25 FULL MATRIX (user directive "lance tout les coin, toutes les stratégies, tous
# les frames, on va accumuler de la donnée"): the old "keep-the-green" curation is replaced
# by "run EVERYTHING in paper, let the data decide". 6 coins × 4 zlead variants × 2 frames
# = 48 crypto runners, generated by the loop below (no hand-kept list to drift).
#
# The zlead family is ONE engine + composable Presets (pmlab/presets.py): zlead
# (flagship, band 0.85-0.95 z>=1, slot 0.27-0.45) + types n (band 0.85-0.90) / x (z>=1.5) /
# mk (maker). Entry slot widened enter_lo 0.35->0.27 (4-6.75min) to maximise CUMULATIVE
# $/day; per-coin enter_lo via COIN_SLOTS (bnb 0.33, auto by --underlying). Real pilots are
# armed via the dashboard (.live_env + Arm), NOT this watchdog.
#
# SETTLEMENT: paper settles on the real Chainlink ORACLE (feeds.resolve_market) + Binance
# proxy fallback. 1h/30m up/down markets DO NOT EXIST on Polymarket; 4h has no edge.
# Watchdog dedups by --state-dir; bracket patterns only. Poll 12s (PnL-neutral, gentler on
# the APIs at 48 runners — poll-rate is a null PnL lever, research/backtest_poll.py).
cd ~/pmlab

# SELF-GUARD: never pile up. The cron fires every 5 min; at ~72 runners a single pass
# can run long, so overlapping crons would ACCUMULATE stuck instances and overload the
# VPS. flock (not pgrep): the old pgrep self-guard counted cron's own `sh -c … watchdog.sh`
# wrapper as a second instance and bailed forever (the whole paper stack stayed down for
# weeks after a reboot) — a lockfile can't self-match.
exec 9>"$HOME/.watchdog.lock"
flock -n 9 || exit 0

COINS="btc eth sol xrp doge bnb"
VARIANTS="zlead zleadx zleadn zleada zleadp"   # paper matrix (60). MÉNAGE 2026-06-27 : zleadmk RETIRÉ (maker saigne, taker>>maker falsifié) → place faite pour zleadp=FLAGSHIP. zleadmk/zleadf restent armables/constructibles, hors matrice. Plafond VPS ~60-72 : retirer un variant avant d'en ajouter
FRAMES="5m 15m"

launch() { # $1=strategy  $2=flags  $3=state_dir  $4=log
  pgrep -f "[m]ain.py.*--state-dir $3( |\$)" > /dev/null || \
    setsid nohup python3 -u main.py --strategy $1 $2 --state-dir $3 >> $4 2>&1 < /dev/null & }

# ---- HOUSEKEEPING — fiabilité 24/7 (paper UNIQUEMENT ; ne touche JAMAIS run_live.py ni
# les live_state_*/ : le glob state_* exclut le préfixe live_state_, et tous les patterns
# sont bracketés + scopés à un --state-dir précis). Tourne AVANT la relance pour que les
# runners ressuscités soient repris dans la même passe.
STALE_MIN=8           # un runner crypto vivant mais sans tick.json frais depuis 8 min (poll
#                       12s → 40× la cadence) est FIGÉ (stall réseau/API) → kill ciblé + relance.
LOG_MAX_MB=50         # au-delà, on tronque le log EN PLACE (garde l'fd append du process vivant).
DISK_WARN=90          # df ≥ 90 % = le tueur lent d'un VPS 24/7 → ligne bruyante.
HEARTBEAT=deploy/watchdog.heartbeat
NOW=$(date +%s); STALE_KILLS=0

# 1) Relance les runners crypto FIGÉS (vivants mais tick.json périmé). Events/copy exclus :
#    leur poll lent (120-600s) rendrait un seuil mtime faux-positif ; le check mort (pgrep)
#    de la relance suffit pour eux. Risque SIGTERM-pendant-écriture négligeable : un process
#    figé est bloqué en I/O réseau, pas en train d'écrire state.json.
for v in $VARIANTS; do for c in $COINS; do for f in $FRAMES; do
  sd="state_${v}_${c}_${f}"; tj="$sd/tick.json"
  if [ -f "$tj" ] && pgrep -f "[m]ain.py.*--state-dir $sd( |\$)" > /dev/null; then
    age=$(( NOW - $(stat -c %Y "$tj") ))
    if [ "$age" -gt $(( STALE_MIN * 60 )) ]; then
      pkill -f "[m]ain.py.*--state-dir $sd( |\$)"
      STALE_KILLS=$(( STALE_KILLS + 1 ))
      echo "$(date -Is) ⚠ runner figé relancé : $sd (tick vieux de ${age}s)"
    fi
  fi
done; done; done
[ "$STALE_KILLS" -gt 0 ] && sleep 3      # laisse les SIGTERM aboutir avant la relance ci-dessous

# 2) Plafonne les logs emballés EN PLACE (cat/printf > fichier = même inode → l'fd append du
#    process survit ; un mv/rename le gèlerait sur l'ancien inode).
shopt -s nullglob
for lf in *.log; do
  [ "$(stat -c %s "$lf")" -gt $(( LOG_MAX_MB * 1024 * 1024 )) ] && \
    { keep=$(tail -n 2000 "$lf"); printf '%s\n' "$keep" > "$lf"; \
      echo "$(date -Is) ✂ log tronqué : $lf"; }
done
shopt -u nullglob

# 3) Garde disque (visible dans le log + le heartbeat).
DISK=$(df -P . | awk 'NR==2{print $5}' | tr -d '%')
[ "${DISK:-0}" -ge "$DISK_WARN" ] && echo "$(date -Is) ⚠ DISQUE à ${DISK}% (seuil ${DISK_WARN}%)"

# THE MATRIX — every variant × coin × frame. enter_lo is per-coin (COIN_SLOTS, automatic).
# SIZING (2026-06-26): WEIGHTED like the real pilot — each bet is 10 % of capital, capped at
# the coin's book depth (presets.COIN_BET_MAX, auto by --underlying), from a $100 start. So
# paper reflects realistic max-capacity throughput, not a token flat $25. (Old: --bankroll
# 1000 --stake 25.) Existing states were recomputed retroactively (tools/recompute_sizing.py).
for v in $VARIANTS; do for c in $COINS; do for f in $FRAMES; do
  launch "$v" "--interval $f --underlying $c --bankroll 100 --weighted --weight-pct 0.10 --poll 12" \
    "state_${v}_${c}_${f}" "${v}_${c}_${f}.log"
done; done; done

# --- EVENT markets: favourite-longshot harvest OFF crypto (paper sim). The crypto edge is
# ~arbitraged; the bias is FATTER on slow, retail, human-priced markets. Scan Gamma for
# binary favourites 0.85-0.95, hold to resolution (run_events.py, separate dedup).
elaunch() { # $1=name  $2=flags  $3=state_dir  $4=log
  pgrep -f "[r]un_events.py.*--state-dir $3( |\$)" > /dev/null || \
    setsid nohup python3 -u run_events.py --name $1 $2 --state-dir $3 >> $4 2>&1 < /dev/null & }
elaunch events-broad "--max-positions 40 --poll 600"                       state_events_broad events_broad.log
elaunch events-fast  "--days-max 5 --max-positions 40 --poll 600"          state_events_fast  events_fast.log
elaunch events-slow  "--days-min 14 --liq-max 1000000 --max-positions 30 --poll 600" state_events_slow events_slow.log

# --- COPY-MIRROR: paper-replicate skilled wallets on crypto THRESHOLD markets ("BTC above
# $X?"), the ONE crypto-Polymarket arena where a SKILL edge survives. Slow markets (entry
# ~48h out) make mirroring feasible. coinman2/06dc = forecasters ; king = NEGATIVE control.
clauch() { # $1=who  $2=state_dir  $3=log
  pgrep -f "[r]un_copymirror.py.*--state-dir $2( |\$)" > /dev/null || \
    setsid nohup python3 -u run_copymirror.py --who $1 --state-dir $2 --poll 120 >> $3 2>&1 < /dev/null & }
clauch coinman2 state_copy_coinman2 copy_coinman2.log
clauch 06dc     state_copy_06dc     copy_06dc.log
clauch king     state_copy_king     copy_king.log

# Optional real-money env for the dashboard's "Arm" button (POLY_PRIVATE_KEY, POLY_SIG_TYPE,
# POLY_FUNDER, POLY_RPC). Absent by default -> the pilot can ONLY run DRY-RUN. Create
# ~/pmlab/.live_env (chmod 600, gitignored) with the exports; the key never enters
# the repo or the code.
[ -f .live_env ] && set -a && . ./.live_env && set +a

# --- dashboard: the full crypto matrix (generated) + the events + copy tabs.
# Morocco DISPLAY dashboard (SPA + paper/events/copy + the pilot tab proxied to the AWS
# engine via --pilot-remote). Single source = deploy/morocco_dash.sh, fed THIS watchdog's
# strat matrix so the list never drifts. (The launch moved out of the watchdog so it can
# also be triggered by hand without tripping the watchdog's own dedup guard.)
COINS="$COINS" VARIANTS="$VARIANTS" FRAMES="$FRAMES" bash deploy/morocco_dash.sh

# --- HEARTBEAT — état de santé en une ligne (lisible d'un coup d'œil / future alerte).
# alive = process crypto vivants ; dash = dashboard up. Écrit à CHAQUE passe (toutes les 5 min)
# donc un heartbeat périmé = le watchdog lui-même est mort.
sleep 2   # laisse les relances ci-dessus apparaître dans le pgrep
ALIVE=$(pgrep -cf "[m]ain.py" 2>/dev/null || echo 0)
EXPECTED=$(( $(echo $VARIANTS | wc -w) * $(echo $COINS | wc -w) * $(echo $FRAMES | wc -w) ))
DASH=$(pgrep -f "[w]ebdash.py" > /dev/null && echo up || echo DOWN)
echo "$(date -Is) alive_crypto=${ALIVE}/${EXPECTED} dash=${DASH} stale_kills=${STALE_KILLS} disk=${DISK:-?}%" > "$HEARTBEAT"
